name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  win:

    runs-on: windows-latest

    permissions:
      checks: write

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          3.1.x
          6.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test (6.0)
      run: dotnet test --no-restore --verbosity normal -f net6.0 /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov --logger "trx;LogFileName=results6.trx"
    - name: Generate unit test report (6.0)
      uses: phoenix-actions/test-reporting@v12
      id: unit-test-report-win6
      if: success() || failure() 
      with:
        name: test results (win net6.0)
        path: Benchly.UnitTests/TestResults/results6.trx
        reporter: dotnet-trx 
        only-summary: 'true'

    - name: Publish NuGet artifacts
      uses: actions/upload-artifact@v3
      with:
        name: NuGet package
        path: Benchly/bin/Release/